---
apiVersion: v1
kind: Service
metadata:
  name: frontend-cs
  labels:
    app: frontend
    name: frontend-cs
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 32080
    name: frontend-port
    protocol: TCP
  selector:
    app: frontend
