apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
  labels:
    app: mongo
    name: mongo-svc
spec:
  type: NodePort
  ports:
  - port: 27017
    nodePort: 32017
    name: mongo-client
    protocol: TCP
  selector:
    app: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-cs
  labels:
    app: mongo
spec:
  ports:
  - port: 27017
    name: mongo-client
  selector:
    app: mongo
---
